### ISSUE TITLE
[ Feature Request ] 添加配置项以允许为插件的命令配置名称

### ISSUE THREAD

**Issue by DynamicLoader** [myunco/LiteTeleport#5]
作者大大您好！

首先感谢您做出如此轻量并且实用的插件！

但是，目前插件几乎所有命令都是写死并且全局可用的，而通过 commands.yml 配置别名将导致命令参数补全无法触发。

是否可以添加几个配置项以允许配置命令别名或者重命名命令呢？

BTW: 如何在本地构建这个插件呢？

Thanks.

**Comment by myunco** [comment]
不知道你说的commands.yml是什么插件提供的，如果你想修改或添加此插件的命令别名，可以用解压缩软件打开插件jar文件，编辑plugin.yml中的commands部分，找到对应的命令，编辑其aliases(如果没有可以按格式手动添加)，以tpaccept为例：
![2](https://user-images.githubusercontent.com/26001944/191973204-46ecec0a-25a7-4a2d-895e-3e50b19e91c4.png)
将 aliases: 'tpyes' 修改为 aliases: ['tpyes','tpok','tpaok'] 表示tpaccept命令的别名为tpyes、tpok和tpaok
```
  tpaccept:
    description: '接受传送请求。'
    usage: '/tpaccept'
    aliases: ['tpyes','tpok']
    permission: 'LiteTeleport.tpaccept'
    permission-message: '§c你没有权限使用此命令!'
```

至于在本地构建，以IDEA为例：
clone项目后，下载一个spigot服务端jar文件放到lib目录(我本地用的是spigot1.13和jdk8)
然后将lib目录中的PlayerPointsAPI-3.1.1.jar、VaultAPI-1.7.1.jar和你放进去的spigot.jar手动添加为依赖
然后打开Project Structure添加一个Artifacts如图：
![3](https://user-images.githubusercontent.com/26001944/191976516-bacbdc60-87a2-4204-b8fe-6ef54dbbe5c7.png)
双击compile output将其添加到Output Layout，勾选Include in project build，然后ok即可

此时 构建项目时会自动将插件打包到指定的输出目录：
![image](https://user-images.githubusercontent.com/26001944/191976972-e6178d73-de04-4e4b-94b3-8d3946cb8d3a.png)
